### ISSUE TITLE
MVS-72

### ISSUE THREAD

**Issue by aymericdevriesere** [OPEN-ENT-NG/vie-scolaire#40]
Issue concernant le ticket [ MVS-51 ]. Le but est de créer des routes API pour la mangement des groupings (création, modification, peuplement, suppression).
 https://jira.support-ent.fr/browse/MVS-72
- [ ] #41
- [ ] #44
- [ ] Delete class and group from grouping

**Comment by BastienBenard** [comment]
fix in https://github.com/OPEN-ENT-NG/vie-scolaire/pull/53
